name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:18.09-dind
        options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t vllm-cu118:latest .

      - name: Save image as artifact
        run: docker save vllm-cu118:latest -f vllm-cu118.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: vllm-cu118.tar
