name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:18.09-dind
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker client
        run: |
          echo "DOCKER_HOST=tcp://docker:2375" >> $GITHUB_ENV
          echo "DOCKER_TLS_VERIFY=0" >> $GITHUB_ENV
          echo "DOCKER_CERT_PATH=" >> $GITHUB_ENV

      - name: Verify Docker version
        run: |
          docker version
          docker info

      - name: Build image
        run: docker build -t vllm-cu118:latest .

      - name: Save image as artifact
        run: docker save vllm-cu118:latest -o vllm-cu118.tar --platform linux/amd64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: vllm-cu118.tar
